plugins_path: exp-plugins
plugins_work_dir: exp-workdir
plugins_spring_url_replace_enable: true
exp_object_field_config_json: '[
{
	"className": "com.mqttsnet.thinglinks.open.exp.adapter.springboot3.ResModel",
	"fieldModelsDesc": [{
		"fieldType": "java.lang.String",
		"fieldName": "email"
	}]
}
]'

server:
  port: 8080
